apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smile
  name: smile
spec:
  replicas: 4
  selector:
    matchLabels:
      app: smile
  template:
    metadata:
      labels:
        app: smile
    spec:
      containers:
      - name: smile
        image: edvindza/smile:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m  
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smile
spec:
  selector:
    matchLabels:
      app: smile
  template:
    metadata:
      labels:
        app: smile
    spec:
      containers:
      - name: smile
        image: edvindza/smile:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m  
          limits:
            cpu: 500m
            memory: 512Mi
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smile
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
